### ISSUE TITLE
Getting an Object reference is not set to instance of an object error while parsing opinion

### ISSUE THREAD

**Issue by chetankumar** [gabriele-tomassetti/getting-started-with-antlr-in-csharp#1]
Hi,

I'm running the project right out of the box, with no modifications. When I enter a text like "Chetan says hello", and terminate with EOF (Control-D), it produces an error.

It is able to parse the name correctly, but not the opinion.

```
NameContext name = context.name();
OpinionContext opinion = context.opinion();

SpeakLine line = new SpeakLine() { Person = name.GetText(), Text = opinion.GetText().Trim('"') };
Lines.Add(line);
```

The opinion.GetText() throws the error as the opinion is always null.

**Comment by gabriele-tomassetti** [comment]
Originally the format was different, the **opinion** was not enclosed between double quotes, now it is. We updated the article some time ago, and now the format needs you to put the opinion like in the following example:

`Chetan says "hello"` (plus the newline)

We updated the article with the new changes, but I just noticed that we forgot to update the code regarding the tests in the article (we updated the code in the project). So, that is where the confusion might come from. Sorry for the error.

I would also add that, if you are trying to test the finished program, you should add two lines:
```
Chetan says "hello"
Chetan says "bye"
```
