### ISSUE TITLE
Speak.g4 slightly different in article than repo

### ISSUE THREAD

**Issue by mika76** [gabriele-tomassetti/getting-started-with-antlr-in-csharp#2]
The reason I bring it up is that the last test failed since I am working on a mac and the last assert was looking for the last `\n` which was missing... Replacing the g4 file with the one in the repo makes it work.

**Comment by gabriele-tomassetti** [comment]
Thanks for reporting this error. We fixed it. Unfortunately this issue keep re-occurring because sometimes the slash `\` disappears from articles on WordPress. We have not yet figured out why that happens, but it happens sporadically.
